plugins {
    id 'java'
    id 'application'
}

group = 'practice'
version = '0.0.1'

java {
    sourceCompatibility = JavaVersion.VERSION_17
}

compileJava.options.encoding = 'UTF-8'
compileTestJava.options.encoding = 'UTF-8'
compileJava.options.compilerArgs += ['-parameters']
compileTestJava.options.compilerArgs += ['-parameters']

tasks.withType(JavaExec).configureEach {
    jvmArgs '-Dfile.encoding=UTF-8', '-Dstdout.encoding=UTF-8', '-Dstderr.encoding=UTF-8'
}

tasks.withType(Test).configureEach {
    jvmArgs '-Dfile.encoding=UTF-8'
}


repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework:spring-context:6.1.14'
    implementation 'org.aspectj:aspectjweaver:1.9.22'
    implementation 'jakarta.annotation:jakarta.annotation-api:2.1.1'
    implementation 'org.springframework.boot:spring-boot:3.2.11'
    implementation 'com.h2database:h2:2.2.224'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'org.springframework:spring-jdbc:6.1.14'
    implementation 'org.springframework:spring-web:6.1.14'
    implementation 'org.springframework:spring-webmvc:6.1.14'
    implementation 'jakarta.servlet:jakarta.servlet-api:6.0.0'
    implementation 'org.apache.tomcat.embed:tomcat-embed-core:10.1.31'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.17.2'
    implementation 'org.hibernate.orm:hibernate-core:6.4.4.Final'
    implementation 'org.springframework.data:spring-data-jpa:3.2.5'
    implementation 'org.springframework:spring-orm:6.1.14'
    implementation 'org.springframework.security:spring-security-core:6.2.4'
    implementation 'org.springframework.security:spring-security-web:6.2.4'
    implementation 'org.springframework.security:spring-security-config:6.2.4'
    implementation 'org.springframework.security:spring-security-crypto:6.2.4'
    implementation 'org.springframework.data:spring-data-redis:3.2.5'
    implementation 'io.lettuce:lettuce-core:6.3.2.RELEASE'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    implementation 'ch.qos.logback:logback-classic:1.5.6'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

application {
    mainClass = project.findProperty('mainClass') ?: 'practice.phase2.Main'
}

test {
    useJUnitPlatform()
}
